_4th_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',RedirectView.as_view(url='uauth/')),
    path('uauth/', include('uauth.urls')),
    path('chat/', include('chat.urls')),
    path('chat_choice/', views.chat_choice, name='chat_choice'),
    path('delete_chat/', views.delete_chat, name='delete_chat'),
    path('deleted_chat/', views.deleted_chat, name='deleted_chat'),
    
]

chat/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from chat import views

app_name = 'chat'

urlpatterns = [
    path('',views.chat_main, name='chat_main'),
    path('withdraw/', views.withdraw_view, name='withdraw'),
    path('logout/',views.logout_view, name='logout'),
    path('chat_choice/', views.chat_choice, name='chat_choice'),
    path('save_message/', views.save_message, name='save_message'),
    path('chat_list/', views.chat_list_view, name='chat_list'),
    path('<int:chat_id>/', views.chat_main, name='chat_main_with_id'),
    path('create_chat/', views.create_chat, name='create_chat'),
    path('delete_chat/', views.delete_chat, name='delete_chat'),
    path('change_pw/', views.change_password, name='change_pw'),
    path('check_old_password/',views.check_old_password,name="check_old_password"),
]

uauth/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from uauth import views

app_name = 'uauth'

urlpatterns = [
    path('',views.main, name='main'),
    path('login/',views.login_view,name='login'),
    path('signup/', views.signup, name='signup'),
    path('send_code/', views.send_verification_code, name='send_code'),
    path('verify_code/',views.verify_code,name='verify_code'),
    path('verify/', views.verify_code, name='verify'),
    path('check_email/', views.check_email, name='check_email'),
    path('findpw/',views.findpw, name='findpw'),
    path('modify_pw/',views.modify_pw, name='modify_pw'),
]

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}떠나봄{% endblock %}</title>
    <link rel = 'stylesheet' href="{% static 'css/main.css' %}">
    {% block extra_head %}{% endblock extra_head %}
    {% block style %}
    {% endblock style %}
</head>
<body>
    {% include 'layout/header.html' %}

    <main>
        {% block content %}
        
        
        {% endblock content %}
    </main>
    {% block script %}
    
    {% endblock script %}
</body>
</html>

templates/layout/header.html
{% load static %}
<header>
    {% if '/chat/' in request.path %}
        <a href="{% url 'chat:chat_main' %}">
            <img src="{% static 'images/logo.png' %}" alt="로고"/>
        </a>
    {% else %}
        <a href="{% url 'uauth:main' %}">
            <img src="{% static 'images/logo.png' %}" alt="로고"/>
        </a>
    {% endif %}
    <span>떠나봄</span>
</header>